// 설명과 코드는 학습용 예시이며 학생 저장소의 구현을 복제한 것이 아닙니다.
const links = {
  hex: ['카카오뱅크 · 멀티모듈 헥사고날 아키텍처 적용기','https://tech.kakaobank.com/posts/2311-hexagonal-architecture-in-messaging-hub/','실제 서비스에서 경계를 어떻게 나눴는지 읽어보세요.'],
  mock: ['카카오 · Mocking으로 생산성까지 챙기는 FE 개발','https://tech.kakao.com/posts/458','네트워크 요청을 가로채 모의 응답을 주는 MSW 사례입니다.'],
  test: ['카카오페이 · 실전에서 TDD하기','https://tech.kakaopay.com/post/implementing-tdd-in-practical-applications/','테스트를 먼저 쓰는 과정과 설계의 관계를 살펴보세요.'],
  strategy: ['토스 · 가치있는 테스트를 위한 전략과 구현','https://toss.tech/article/test-strategy-server','테스트 대역과 실제 객체 사이의 선택을 읽어보세요.'],
  stock: ['우아한형제들 · 선물하기 시스템의 상품 재고 관리','https://techblog.woowahan.com/2709/','재고 차감에서 동시성과 저장소 경계가 왜 중요한지 보는 심화 사례입니다.'],
  idem: ['토스페이먼츠 · 인증 및 기타 헤더 설정','https://docs.tosspayments.com/reference/using-api/authorization','멱등키를 실제 API 요청에 어떻게 전달하는지 확인하세요.'],
  auth: ['Velog · 헷갈리는 인증 개념 정리','https://velog.io/@sunmins/헷갈리는-인증-개념-JWT-Bearer-Access-Token-Session-Storage-정리','기존 리뷰에서 소개된 개인 블로그입니다. 아래 학습 설명과 함께 비교해 읽으세요.']
};
export const lessons = [
 {id:'ports',group:'구조와 설계',title:'포트와 헥사고날',terms:['port','헥사고날','ingest','어댑터'],
 intro:'포트는 업무 코드가 외부에 요구하는 약속입니다. 어댑터는 그 약속을 실제 기술로 수행하는 코드예요.',
 analogy:'콘센트 규격이 같으면 조명을 바꿔도 벽의 배선을 다시 하지 않죠. 다만 인터페이스 하나가 있다고 건물 전체 설계가 정해지는 건 아닙니다.',
 explain:'Spring 서비스가 GitHub SDK를 바로 쓰면 수집 방식이 바뀔 때 서비스도 수정됩니다. CommitReader라는 인터페이스를 내부에 두고 외부 구현체가 이를 구현하면, 업무는 약속에 의존하고 기술은 바깥에서 연결합니다. 이처럼 안쪽 업무를 외부 기술로부터 보호하는 의존 방향이 헥사고날의 핵심입니다. ingest는 외부 데이터를 받아 내부에서 쓸 형태로 들여오는 수집 과정이라는 뜻입니다.',
 nodes:['업무 서비스','CommitReader 포트','선택한 어댑터','커밋 목록'],
 scenarios:[{name:'GitHub API로 수집',steps:['카드 서비스가 커밋 목록을 요청합니다. GitHub SDK는 모릅니다.','CommitReader.read(repo)라는 약속을 호출합니다.','GitHubAdapter가 HTTP 요청을 보내고 외부 응답을 변환합니다.','업무 코드가 내부 Commit 목록으로 계속 작업합니다.']},{name:'테스트용 수집기로 교체',steps:['동일한 업무 서비스를 테스트합니다.','동일한 CommitReader.read(repo)를 호출합니다.','FakeAdapter가 준비된 커밋을 반환합니다. 외부 네트워크는 쓰지 않습니다.','서비스 코드를 고치지 않고 성공·실패 사례를 검증할 수 있습니다.']}],
 code:'interface CommitReader {\n  List<Commit> read(String repo);\n}\nclass IngestService {\n  private final CommitReader reader; // 외부 SDK 대신 약속에 의존\n}',
 caution:'“GitHub 접근은 ingest에서만”은 모듈의 책임을 제한하는 이유입니다. 포트는 기술 의존을 뒤집고 테스트 대역이나 다른 연동 구현을 연결할 때 의미가 있습니다. 교체 계획만이 유일한 이유는 아닙니다.',
 question:'인터페이스가 하나 있으면 전면 헥사고날일까요?',options:['그렇다','의존 방향과 경계도 봐야 한다'],answer:1,feedback:'포트의 존재보다 업무 코드가 어떤 기술에 의존하는지, 어댑터가 어디에 있는지가 중요합니다.',read:['hex'],source:'kyungpook-1-pr-4.md'},
 {id:'monolith',group:'구조와 설계',title:'레이어드와 모듈러 모놀리스',terms:['모놀리스','레이어드','모듈','DDD'],
 intro:'레이어드는 기술 역할로 층을 나누는 방식이고, 모듈러 모놀리스는 하나로 배포하면서 업무별 경계를 지키는 구조입니다.',
 analogy:'한 병원 건물 안에 내과·외과가 있고, 각 과 안에 접수·진료·수납이 있을 수 있습니다. 건물 수, 진료과, 업무 단계는 서로 다른 기준이에요.',
 explain:'controller/service/repository는 요청·업무·저장의 역할입니다. card/ingest/agent는 카드·수집·AI라는 업무 경계입니다. card 모듈 안에 controller/service/repository가 있어도 됩니다. DDD는 업무의 언어와 모델·경계를 설계하는 접근이며 특정 폴더 배치 자체를 의미하지 않습니다.',
 nodes:['한 서버로 배포','ingest 수집','recommend 후보','card 카드'],
 scenarios:[{name:'허용된 모듈 협력',steps:['전체 애플리케이션을 하나의 실행 단위로 띄웁니다.','ingest가 GitHub 기록을 수집합니다.','recommend가 정해진 규칙으로 후보를 좁힙니다.','card가 공개된 모듈 API를 이용해 카드를 만듭니다.']},{name:'경계를 넘는 접근',steps:['하나로 배포한다는 점은 같습니다.','card가 ingest의 내부 저장소를 직접 참조하려 합니다.','의존성 규칙 검사에서 금지된 참조가 발견됩니다.','모듈의 공개 API를 통해 접근하도록 고칩니다.']}],
 code:'card/\n  controller/\n  service/\n  repository/\ningest/\n  api/        // 다른 모듈에 공개\n  internal/   // 내부 구현',
 caution:'레이어드라서 테스트로 의존을 막을 수 없다는 말은 지나칩니다. 패키지 규칙이나 빌드 모듈로도 제한할 수 있습니다. 모듈러 모놀리스와 레이어드는 함께 사용할 수 있습니다.',
 question:'모듈이 8개면 서버도 8개일까요?',options:['항상 8개다','하나로 배포할 수 있다'],answer:1,feedback:'코드의 모듈과 운영 중인 프로세스 수는 별개입니다.',read:['hex'],source:'kyungpook-1-pr-4.md'},
 {id:'boundary',group:'구조와 설계',title:'경계 테스트와 TDD',terms:['ModuleBoundaryTest','경계','TDD','CI'],
 intro:'아키텍처 경계 테스트는 “이 패키지가 저 패키지를 참조하면 안 된다”는 구조 규칙을 자동 검사합니다.',
 analogy:'건축 설계의 방화벽 위치를 검사하는 것과, 실제 소화기가 작동하는지 검사하는 것은 서로 다른 검사입니다.',
 explain:'경계 테스트는 의존 구조를, 업무 테스트는 결과를 확인합니다. TDD는 실패하는 테스트 → 최소 구현 → 정리의 개발 과정입니다. 경계 테스트를 먼저 작성한 것만으로 TDD를 했다고 할 수는 없습니다. CI는 PR의 정해진 이벤트에 이런 검사를 실행하는 자동화 환경입니다.',
 nodes:['PR 작성','코드 의존 분석','규칙 비교','CI 결과'],
 scenarios:[{name:'evidence → agent 참조 추가',steps:['개발자가 근거 검증에서 LLM 서비스를 참조합니다.','검사기가 evidence에서 agent로 가는 의존을 찾습니다.','금지된 방향이므로 규칙 위반입니다.','검사가 실패합니다. 필수 체크로 설정해야 병합까지 차단됩니다.']},{name:'검사할 업무 클래스가 없음',steps:['아직 패키지 설명만 있고 업무 코드가 없습니다.','검사할 대상 클래스가 발견되지 않습니다.','빈 대상 허용 설정이면 위반 없이 통과할 수 있습니다.','통과했다고 업무 검증까지 증명된 것은 아닙니다.']}],
 code:'// 학습용 ArchUnit 규칙 예시\nnoClasses().that().resideInAPackage("..evidence..")\n  .should().dependOnClassesThat()\n  .resideInAPackage("..agent..");',
 caution:'경계 테스트는 직접 HTTP로 LLM을 호출하는 동작까지 자동으로 이해하지 않습니다. 모든 LLM 클라이언트 위치를 제한하는 규칙도 함께 설계해야 합니다.',
 question:'경계 테스트가 통과하면 SHA 검증 기능도 정상일까요?',options:['아니다. 업무 테스트가 따로 필요하다','그렇다'],answer:0,feedback:'참조 구조와 실제 동작의 정확성은 서로 다른 검증 대상입니다.',read:['test','strategy'],source:'kyungpook-1-pr-4.md'},
 {id:'auth',group:'인증과 데이터',title:'인증·인가와 UUID',terms:['UUID','BIGINT','인가','소유자','public_id'],
 intro:'인증은 “누구인가”, 인가는 “이 자원을 볼 수 있는가”입니다. UUID는 주소를 추측하기 어렵게 만들지만 권한을 확인해주지는 않습니다.',
 analogy:'신분증을 확인했다고 남의 사물함을 열 수는 없어요. 사물함 번호를 길게 바꿔도 주인 확인은 여전히 필요합니다.',
 explain:'로그인한 userId를 서버에서 확인한 다음, 카드의 public_id와 소유자 user_id를 같이 조회합니다. BIGINT는 내부 조인용으로, UUID는 외부 식별자로 함께 쓸 수 있습니다. 컬럼과 고유 인덱스의 저장 공간·쓰기 비용이 늘지만 실제 비용은 데이터량과 DB 구현에 따라 다릅니다.',
 nodes:['사용자 A 요청','로그인 확인','소유권 조회','응답'],
 scenarios:[{name:'내 카드 UUID 요청',steps:['사용자 A가 카드 UUID를 전달합니다.','서버가 세션에서 사용자 A를 확인합니다.','UUID와 A의 userId로 조회한 카드가 있습니다.','카드 내용을 반환합니다.']},{name:'남의 카드 UUID를 알아냄',steps:['사용자 A가 사용자 B의 UUID를 전달합니다.','A가 로그인했다는 사실은 여전히 유효합니다.','UUID와 A의 userId를 모두 만족하는 카드는 없습니다.','내용을 반환하지 않습니다. 정책에 따라 404 또는 403을 응답합니다.']}],
 code:'SELECT * FROM card\nWHERE public_id = :requestedId\n  AND user_id = :authenticatedUserId;\n// userId는 요청 본문을 신뢰하지 않고 인증 결과에서 얻습니다.',
 caution:'랜덤 UUID도 노출될 수 있습니다. UUID 버전에 따라 시간 정보 등이 포함될 수 있어 “모든 UUID가 완전히 무작위”인 것도 아닙니다.',
 question:'UUID를 안다는 이유만으로 카드 조회를 허용해도 될까요?',options:['안 된다. 소유권을 확인해야 한다','길고 복잡하니 괜찮다'],answer:0,feedback:'추측하기 어려운 식별자는 인가의 대체물이 아닙니다.',read:['auth'],source:'kyungpook-1-pr-4.md'},
 {id:'session',group:'인증과 데이터',title:'세션·쿠키·JWT·Bearer',terms:['세션','JWT','Bearer','쿠키','session'],
 intro:'세션과 JWT, 쿠키와 Bearer는 같은 기준의 양자택일이 아닙니다. 상태를 확인하는 방법, 토큰 형식, 전달 방법을 나눠 생각하세요.',
 analogy:'보관소에 맡긴 짐을 찾는 번호표가 세션 ID라면, 서명을 확인할 수 있는 증명서는 JWT에 가깝습니다. 쿠키와 헤더는 그것을 전달하는 봉투에 해당합니다.',
 explain:'서버 세션은 세션 ID로 로그인 상태를 조회합니다. JWT는 서명과 만료 등을 검증할 수 있는 토큰 형식입니다. 쿠키는 브라우저가 조건에 맞춰 자동 전송하고, Authorization: Bearer는 토큰을 헤더에 싣는 방식입니다. 불투명 세션 토큰을 Bearer로 보낼 수도, JWT를 쿠키에 넣을 수도 있습니다.',
 nodes:['로그인 성공','브라우저 보관','다음 요청','서버 확인'],
 scenarios:[{name:'서버 세션 + 쿠키',steps:['서버가 세션 저장소에 사용자와 만료를 저장합니다.','Set-Cookie로 불투명 세션 ID를 전달합니다.','브라우저가 도메인·경로·보안 조건에 맞는 Cookie를 보냅니다.','서버가 세션 저장소에서 사용자와 유효기간을 확인합니다.']},{name:'JWT + Bearer 헤더',steps:['서버가 사용자 식별자와 exp 등을 담아 JWT에 서명합니다.','클라이언트가 토큰을 보관합니다. 저장 위치는 별도 보안 설계입니다.','클라이언트가 Authorization: Bearer <token>을 보냅니다.','서버가 서명·발급자·대상·만료 및 필요한 폐기 상태를 검증합니다.']}],
 code:'// 쿠키를 통한 세션 전달 예시\nSet-Cookie: SID=random; HttpOnly; Secure; SameSite=Lax\n\n// Bearer는 JWT만을 뜻하지 않습니다.\nAuthorization: Bearer opaque-session-token',
 caution:'JWT도 폐기 목록·사용자 버전 검사로 조기 차단할 수 있습니다. 다만 상태 조회가 추가됩니다. HttpOnly는 JS의 쿠키 읽기를 제한하지만 XSS 자체를 해결하지는 않습니다. 서버 세션 만료와 쿠키 만료도 별도 설정입니다.',
 question:'Bearer 토큰이면 반드시 JWT일까요?',options:['맞다','불투명 세션 토큰일 수도 있다'],answer:1,feedback:'Bearer는 소지한 토큰을 제시하는 인증 방식이고 JWT는 토큰 형식입니다.',read:['auth','idem'],source:'pusan-3-pr-29.md'},
 {id:'transaction',group:'동시성과 신뢰성',title:'트랜잭션과 롤백',terms:['트랜잭션','롤백','transaction','탈퇴'],
 intro:'트랜잭션은 함께 성공하거나 함께 취소되어야 하는 DB 변경을 묶습니다. 외부 API까지 자동으로 되돌려주지는 않습니다.',
 analogy:'은행에서 출금만 하고 입금에 실패하면 곤란하죠. 두 DB 변경을 묶을 수 있지만 이미 보낸 문자까지 취소되는 것은 아닙니다.',
 explain:'어느 계층에 @Transactional을 달지보다 어떤 변경이 하나의 업무인지 먼저 봐야 합니다. 여러 서비스의 DB 변경이 한 업무라면 더 바깥의 유스케이스에서 묶을 수 있습니다. 외부 소셜 연결 해제나 별도 Redis 연산은 일반적인 DB 트랜잭션의 롤백 범위 밖입니다.',
 nodes:['업무 시작','첫 변경','후속 작업','최종 상태'],
 scenarios:[{name:'같은 DB 변경 중 실패',steps:['같은 DB 트랜잭션을 시작합니다.','사용자 관련 행을 삭제합니다. 아직 커밋하지 않았습니다.','다음 DB 변경에서 예외가 발생합니다.','롤백되면 앞선 삭제도 취소됩니다. 예외·전파 설정이 맞아야 합니다.']},{name:'외부 API 성공 후 DB 실패',steps:['소셜 연결 해제 API를 먼저 호출합니다.','외부 제공자에서 연결 해제가 성공했습니다.','이후 DB 삭제가 실패해 DB 트랜잭션이 롤백됩니다.','외부 연결 해제는 되돌아오지 않습니다. 재시도·보상 정책이 필요합니다.']}],
 code:'@Transactional\npublic void transfer() {\n  debit();  // 같은 트랜잭션의 DB 변경\n  credit(); // 실패 시 전체 DB 변경 롤백\n}\n// HTTP 요청의 효과는 이 롤백에 포함되지 않습니다.',
 caution:'서비스 메서드에 어노테이션을 붙였다는 사실만으로 모든 변경이 묶이지 않습니다. 프록시 호출, 트랜잭션 매니저, 전파와 예외 정책을 함께 확인해야 합니다.',
 question:'DB 롤백 시 성공한 GitHub API 호출도 취소될까요?',options:['아니다','자동으로 취소된다'],answer:0,feedback:'분산된 시스템의 효과는 별도 재시도나 보상 작업으로 다뤄야 합니다.',read:['stock'],source:'kangwon-3-pr-59.md'},
 {id:'atomic',group:'동시성과 신뢰성',title:'원자성과 경쟁 상태',terms:['원자','GETDEL','Rotation','동시','Redis'],
 intro:'원자적 처리는 중간에 다른 요청이 끼어들지 못하도록 하나의 연산으로 처리하는 것입니다.',
 analogy:'마지막 티켓 한 장을 두 사람이 동시에 보고 “있다!”고 확인하면 둘 다 가져가려 합니다. 확인과 가져가기를 한 번에 해야 하죠.',
 explain:'Refresh Token Rotation에서 기존 토큰을 읽고 나중에 삭제하면 두 요청이 모두 같은 토큰을 읽을 수 있습니다. 원자적인 읽기·삭제 연산은 기존 토큰을 한 요청만 소비하게 합니다. 이것은 전체 재발급 흐름의 장애 처리까지 해결한다는 뜻은 아닙니다.',
 nodes:['요청 A','요청 B','토큰 소비','재발급 결과'],
 scenarios:[{name:'GET 다음 DEL로 분리',steps:['A가 GET으로 토큰을 읽습니다.','A가 삭제하기 전에 B도 같은 토큰을 읽습니다.','A와 B가 각각 검증하고 DEL을 실행합니다.','두 요청 모두 이미 토큰을 읽었으므로 둘 다 새 토큰을 발급할 위험이 있습니다.']},{name:'GETDEL로 한 번에 소비',steps:['A가 GETDEL로 읽기와 삭제를 함께 수행합니다.','B가 GETDEL을 실행하면 값이 없습니다.','기존 토큰을 가진 요청은 A 하나입니다.','A만 재발급을 진행합니다. 소비 후 장애나 응답 유실 정책은 별도로 필요합니다.']}],
 code:'// 경쟁 가능\ntoken = redis.get(key);\nredis.del(key);\n\n// 읽기 + 삭제를 한 연산으로\ntoken = redis.getdel(key);\nif (token == null) reject();',
 caution:'Redis 단일 명령이 원자적이어도 여러 명령의 조합은 자동으로 원자적이지 않습니다. 검증 전에 무조건 삭제하면 잘못된 요청이 정상 토큰을 소비할 수 있으므로 키·토큰 검증 설계도 필요합니다.',
 question:'GET과 DEL이 각각 안전하면 둘의 조합도 항상 안전할까요?',options:['그렇다','그 사이 다른 요청이 들어올 수 있다'],answer:1,feedback:'경쟁 상태는 두 연산 사이의 빈틈에서 발생합니다.',read:['stock'],source:'kangwon-3-pr-59.md'},
 {id:'idempotency',group:'동시성과 신뢰성',title:'멱등성과 중복 요청',terms:['멱등','Idempotency','idempotency','중복'],
 intro:'멱등성은 같은 요청을 반복해도 의도한 효과가 추가로 생기지 않는 성질입니다. 응답이 유실되어 다시 요청할 때 특히 중요합니다.',
 analogy:'엘리베이터 호출 버튼을 여러 번 눌러도 같은 호출 한 건으로 처리되는 것과 비슷합니다.',
 explain:'결제나 분석 생성에서 요청마다 새 작업을 만들면 재시도로 중복이 생깁니다. 같은 업무 요청에 같은 멱등키를 보내고 서버가 키와 요청 내용·처리 상태·결과를 관리하면 중복을 판별할 수 있습니다. 분산 락은 동시 실행을 제한하며, 완료 후 다시 온 요청까지 같은 결과로 처리하는 멱등성과는 다릅니다.',
 nodes:['첫 요청','서버 처리','응답 유실','동일 요청 재시도'],
 scenarios:[{name:'멱등키 있음',steps:['클라이언트가 같은 업무에 key=abc를 발급합니다.','서버가 키를 원자적으로 등록하고 작업 결과를 기록합니다.','처리는 성공했지만 네트워크 문제로 응답이 사라집니다.','같은 키·내용의 재시도에는 기존 결과를 반환합니다.']},{name:'재시도마다 새 키',steps:['첫 요청이 key=abc로 도착합니다.','첫 작업이 정상 처리됩니다.','응답을 못 받은 클라이언트가 재시도합니다.','key=xyz를 새로 만들면 별개 요청으로 취급되어 중복 작업이 생길 수 있습니다.']}],
 code:'POST /analysis-jobs\nIdempotency-Key: abc\n\n// 서버: 사용자 + 키로 중복 판단\n// 같은 키에 다른 요청 내용이면 충돌 처리\n// 처리 중 / 완료 / 실패 상태와 결과 보관',
 caution:'키를 헤더에 넣기만 해서는 멱등성이 생기지 않습니다. 서버의 원자적 중복 등록, 만료 기간, 실패 후 재시도 규칙이 필요합니다.',
 question:'재시도할 때마다 멱등키를 바꾸면 중복을 막을까요?',options:['아니다. 같은 업무 요청에는 같은 키','그렇다'],answer:0,feedback:'서버가 같은 요청임을 알아볼 수 있어야 합니다.',read:['idem'],source:'pusan-3-pr-29.md'},
 {id:'polling',group:'화면과 비동기',title:'Job 폴링과 새로고침',terms:['폴링','jobId','Polling','전역','새로고침'],
 intro:'폴링은 서버에 “끝났나요?”를 주기적으로 묻는 것입니다. 화면 상태와 서버의 실제 작업 상태는 따로 존재합니다.',
 analogy:'식당 진동벨 번호를 메모해두면 화면을 닫았다 돌아와도 주문을 찾을 수 있어요. 메모를 잃었다고 주방의 요리가 사라지지는 않습니다.',
 explain:'POST로 분석을 시작하고 jobId를 받습니다. 화면은 GET으로 상태를 조회하다 완료·실패에서 멈춥니다. 모듈 전역 변수는 화면 전환 중 살아있을 수 있지만 새로고침하면 초기화됩니다. ID 보관 또는 서버의 최근 작업 조회를 통해 복귀할 수 있어야 합니다.',
 nodes:['분석 시작','jobId 수신','화면 새로고침','작업 복구'],
 scenarios:[{name:'메모리에만 jobId 보관',steps:['서버에서 분석 작업을 생성합니다.','브라우저 전역 변수에 jobId를 담습니다.','새로고침으로 JS 메모리가 초기화됩니다.','서버 작업은 계속될 수 있지만 화면은 어떤 작업인지 모릅니다.']},{name:'ID 보관 + 서버 재조회',steps:['서버에서 분석 작업을 생성합니다.','ID를 적절히 보관하거나 최근 작업 조회 경로를 준비합니다.','새로고침 후 인증된 사용자의 작업을 다시 찾습니다.','서버 상태를 조회하고 진행 중이면 폴링을 재개합니다.']}],
 code:'const { jobId } = await startAnalysis();\n// 복귀 시 jobId를 복원한 뒤 서버 상태 재조회\nconst job = await getJob(jobId);\nif (["SUCCEEDED", "FAILED"].includes(job.status)) stopPolling();',
 caution:'ID를 저장하는 것만으로 작업이 재개되지는 않습니다. 서버 작업의 지속성, 소유권 확인, 폴링 중단·오류 재시도·중복 타이머 정리가 필요합니다. 이 페이지의 단계 그림은 실제 백엔드 작업이 아닌 시뮬레이션입니다.',
 question:'새로고침하면 서버 분석 작업도 반드시 사라질까요?',options:['브라우저 메모리와 서버 작업은 별개다','둘 다 반드시 사라진다'],answer:0,feedback:'작업 지속 여부는 서버 구현에 달려 있습니다. 화면은 서버의 현재 상태를 다시 조회해야 합니다.',read:['mock'],source:'kyungpook-1-pr-4.md'},
 {id:'mock',group:'화면과 비동기',title:'Mock·Hook·API 계약',terms:['mock','Mock','hook','스키마','계약','OpenAPI'],
 intro:'화면이 데이터를 어디서 얻는지 모르게 만들면 Mock에서 실제 API로 바꿀 때 화면 수정이 줄어듭니다.',
 analogy:'전광판은 전달받은 도착 시간을 표시합니다. 도착 시간이 연습용 입력인지 실제 버스 서버에서 왔는지는 전광판의 관심사가 아닙니다.',
 explain:'컴포넌트는 데이터를 받아 그립니다. Hook은 조회·로딩·오류 등의 상태를 화면에 제공합니다. API 계약은 요청과 응답의 이름·타입·오류 등을 합의한 문서입니다. OpenAPI로 타입이나 클라이언트를 생성할 수 있지만 도구를 별도로 설정해야 하며, 문서가 있다고 자동 생성되는 것은 아닙니다.',
 nodes:['데이터 제공자','조회 Hook','화면 데이터','컴포넌트'],
 scenarios:[{name:'Mock 데이터 제공',steps:['Mock 제공자가 계약에 맞는 카드 목록을 반환합니다.','useCards가 목록·로딩·오류 상태를 관리합니다.','화면이 같은 구조의 데이터를 받습니다.','CardList는 받은 데이터를 표시합니다.']},{name:'실제 API로 전환',steps:['HTTP API 제공자가 서버 응답을 받습니다.','useCards가 서버 응답을 화면의 데이터 형태로 변환합니다.','로딩·오류·빈 결과도 화면 계약에 포함합니다.','계약이 유지되면 표시 컴포넌트의 변경을 줄일 수 있습니다.']}],
 code:'function HomePage() {\n  const { cards, loading, error } = useCards();\n  if (loading) return <Loading />;\n  if (error) return <ErrorView />;\n  return <CardList cards={cards} />;\n}',
 caution:'Hook을 썼다는 이유만으로 화면 수정이 0이 되지는 않습니다. 실제 페이지네이션·권한·오류·빈 상태가 Mock에 없었다면 UI도 보완해야 합니다.',
 question:'컴포넌트가 MOCK_CARDS를 직접 읽으면 어디를 수정해야 할까요?',options:['서버만','해당 컴포넌트의 데이터 연결도'],answer:1,feedback:'데이터 접근이 컴포넌트 안에 묶여 있기 때문입니다.',read:['mock'],source:'kyungpook-1-pr-4.md'},
 {id:'evidence',group:'AI와 검증',title:'LLM 생성과 결정적 검증',terms:['LLM','sha','SHA','evidence','근거','검증'],
 intro:'문장을 만드는 작업과 사실을 확인하는 작업은 다릅니다. 그럴듯한 SHA를 만드는 것과 실제 커밋을 조회하는 것은 다르죠.',
 analogy:'작가는 사건을 설명하고, 편집자는 취재 기록을 확인합니다. 확인할 기록이 없다면 문장을 더 자연스럽게 바꾸어도 근거가 생기지는 않아요.',
 explain:'LLM이 카드 초안을 만들고 커밋 SHA를 붙였다면, 검증기는 실제 GitHub 기록에서 존재·저장소·작성자·내용의 관련성을 확인해야 합니다. 결정적 재조회는 같은 권위 데이터와 규칙에 기반해 판정한다는 뜻입니다. 외부 서비스 상태까지 영원히 같다는 의미는 아닙니다.',
 nodes:['LLM 초안','SHA 추출','실제 기록 조회','카드 확정 판단'],
 scenarios:[{name:'존재하지 않는 SHA',steps:['모델이 그럴듯한 설명과 SHA를 생성합니다.','검증 코드가 근거 식별자를 읽습니다.','해당 저장소에서 커밋을 찾지 못합니다.','근거 없음으로 표시하고 확정을 막거나 보완을 요구합니다.']},{name:'SHA는 존재하지만 다른 기여',steps:['모델이 실제 SHA를 붙였습니다.','검증기가 식별자를 읽습니다.','커밋은 있지만 대상 사용자·설명과의 관련성이 맞지 않습니다.','존재만으로 통과하지 않고 관련 근거인지 추가 판단합니다.']}],
 code:'Commit commit = github.find(repo, sha);\nif (commit == null) return MISSING;\nif (!belongsToTarget(commit)) return WRONG_CONTEXT;\n// 존재 검증만으로 서술의 사실성이 완전히 증명되지는 않습니다.',
 caution:'후보 압축에 LLM을 쓰지 않는다는 프로젝트 선택과 FastAPI라는 프레임워크는 별개입니다. FastAPI도 일반 HTTP 로직을 실행하며, GitHub API 호출 자체가 LLM 호출은 아닙니다.',
 question:'SHA가 실재하면 카드의 모든 서술이 사실일까요?',options:['그렇다','내용·작성자·맥락도 확인해야 한다'],answer:1,feedback:'식별자 존재는 근거 검증의 시작입니다.',read:['strategy'],source:'kyungpook-1-pr-4.md'},
 {id:'evaluation',group:'AI와 검증',title:'AI 평가와 테스트 픽스처',terms:['픽스처','평가','오탐','지표','verification'],
 intro:'평가 지표 하나만 좋아져도 서비스가 좋아졌다고 할 수는 없습니다. 무엇을 틀렸는지 나눠 봐야 합니다.',
 analogy:'모든 문제에 “모르겠다”라고 쓰면 틀린 답은 줄어듭니다. 하지만 시험을 잘 본 것은 아니죠.',
 explain:'픽스처는 반복 평가에 쓸 입력과 기대 판단의 묶음입니다. 충분한 근거·부족한 근거·혼동하기 쉬운 사례를 함께 준비하세요. 근거 없는 확정 비율뿐 아니라 답해야 할 때 답했는지, 잘못된 도구를 골랐는지, 판단을 회피했는지를 같이 봐야 합니다.',
 nodes:['평가 사례','모델 응답','정답 기준 대조','지표 해석'],
 scenarios:[{name:'모든 질문에 정보 부족',steps:['근거 충분 5개와 근거 부족 5개를 준비합니다.','모델이 10개 모두 정보 부족이라고 답합니다.','근거 없는 확정은 0건입니다.','하지만 답할 수 있는 5개도 놓쳤습니다. 확정 오류율 하나로는 부족합니다.']},{name:'조건별로 판단',steps:['같은 10개 사례와 기대 판단을 사용합니다.','충분한 5개는 답하고 나머지는 보류합니다.','판단 근거와 도구 선택도 함께 대조합니다.','이 예시에서는 올바른 완료와 올바른 보류 모두 확인됩니다.']}],
 code:'fixtures = [\n  { evidence: "충분", expected: "판단 완료" },\n  { evidence: "부족", expected: "보류" },\n  { evidence: "혼동 가능", expected: "추가 확인" }\n];',
 caution:'그림의 10개는 설명용 수치입니다. 실제 모델 성능 측정값이 아닙니다. 평가 데이터와 프롬프트 조정용 데이터를 구분하고 반복 측정 조건도 기록하세요.',
 question:'근거 없는 확정이 0이면 무조건 좋은 모델일까요?',options:['필요한 판단도 회피했는지 봐야 한다','그렇다'],answer:0,feedback:'오류 억제와 유용한 판단의 균형을 함께 확인해야 합니다.',read:['strategy'],source:'kangwon-3-pr-59.md'}
];
export function readingFor(lesson) { return lesson.read.map(key => links[key]); }
